const sliderData =[
    {
      "id": 1,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 2,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 3,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 4,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 5,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 6,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 7,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 8,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    },
    {
      "id": 9,
      "team1": "Majhi Mumbai",
      "team2": "Tiigers Of Kolkata",
      "logo1": "/images/logo1.png",
      "logo2": "/images/kolkataTiger1.png",
      "score1": "58/9",
      "overs1": "10.0 OV",
      "score2": "60/0",
      "overs2": "7.4 OV",
      "stadium": "Dadoji Kondadev Stadium",
      "liveStatus": "Live •",
      "winMsg": "Tiigers Of Kolkata won the toss elected to bat",
      "category": "FINAL"
    }
]
export default sliderData;